import type { Metadata } from "next";
import Link from "next/link";
import { LegalDraftDisclaimer } from "@/components/legal-draft-disclaimer";

export const metadata: Metadata = {
  title: "Terms of Service — Vocis",
  description:
    "Terms governing use of the Vocis website, web trial, and mobile apps.",
};

export default function TermsPage() {
  return (
    <main className="min-h-dvh bg-[#050508] px-4 py-10 text-zinc-300 sm:px-6 sm:py-14">
      <div className="mx-auto max-w-3xl">
        <Link
          href="/"
          className="text-sm font-medium text-violet-400 hover:text-violet-300"
        >
          ← Home
        </Link>
        <h1 className="mt-8 text-3xl font-semibold tracking-tight text-white">
          Terms of Service
        </h1>
        <p className="mt-2 text-sm text-zinc-500">
          Last updated: April 12, 2026
        </p>

        <div className="mt-10 space-y-8 text-sm leading-relaxed">
          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">Agreement</h2>
            <p>
              By accessing or using Vocis—including the{" "}
              <strong>website</strong>, the{" "}
              <strong>30-second browser trial</strong>, any{" "}
              <strong>signed-in web features</strong>, and{" "}
              <strong>mobile applications</strong> we make available—you agree to
              these Terms. If you do not agree, do not use the service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">The service</h2>
            <p>
              Vocis provides AI-assisted interview practice using third-party AI
              (including Google Gemini). The website trial is a limited
              demonstration. Longer sessions, on-device history, and post-session
              scoring may be available through our mobile apps, and cloud-synced
              history may be available when you use signed-in website features, as
              described on the site.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">Acceptable use</h2>
            <ul className="list-disc space-y-2 pl-5">
              <li>
                Do not use Vocis for unlawful, harmful, harassing, or deceptive
                purposes.
              </li>
              <li>
                Do not attempt to overload, disrupt, or reverse-engineer the
                service beyond what is permitted by law.
              </li>
              <li>
                Do not misuse Vocis APIs (including automated scraping, credential
                sharing, or attempts to bypass rate limits or security controls).
              </li>
              <li>
                Do not submit highly sensitive secrets (passwords, API keys,
                classified information) into prompts or audio.
              </li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">
              Mobile app and your data
            </h2>
            <p>
              Depending on the build, interview history and scores may be stored{" "}
              <strong>only on your device</strong>. You are responsible for device
              security, backups, and any loss of local data if you uninstall the app
              or reset your device. Content you provide (including voice, role text,
              job descriptions, and resume-derived text) is processed so we can
              deliver the interview and feedback, as described in the Privacy Policy.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">
              AI output disclaimer
            </h2>
            <p>
              Outputs are generated by artificial intelligence and may be
              inaccurate, incomplete, or inappropriate. Vocis is not a
              substitute for professional career, legal, or human resources
              advice. You remain responsible for how you use suggestions in real
              interviews or decisions.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">
              No warranty; limitation of liability
            </h2>
            <p>
              THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF
              ANY KIND, EXPRESS OR IMPLIED, TO THE MAXIMUM EXTENT PERMITTED BY
              LAW. TO THE MAXIMUM EXTENT PERMITTED BY LAW, VOCIS AND ITS
              CONTRIBUTORS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
              SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF
              PROFITS OR DATA, ARISING FROM YOUR USE OF THE SITE OR TRIAL.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">Termination</h2>
            <p>
              We may suspend or discontinue the website, trial, APIs, or apps, or
              block abuse, at any time without notice.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">Governing law</h2>
            <p>
              These Terms are governed by the laws of the United States and the
              State of Delaware, without regard to conflict-of-law rules, except
              where mandatory consumer protections in your country apply.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-white">Contact</h2>
            <p>
              For questions about these Terms, use the contact information shown
              on the Vocis home page.
            </p>
          </section>
        </div>

        <LegalDraftDisclaimer />
      </div>
    </main>
  );
}
